<a href="https://colab.research.google.com/github/sztabamarta-lgtm/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

1D Array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type (x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [13]:
x.dtype

dtype('float64')

2D Array

In [14]:
x = np.array([[1, 2,3], [-3, 1,3], [5, 6,8], [7,8,9]])
print(x)
x

[[ 1  2  3]
 [-3  1  3]
 [ 5  6  8]
 [ 7  8  9]]


array([[ 1,  2,  3],
       [-3,  1,  3],
       [ 5,  6,  8],
       [ 7,  8,  9]])

In [15]:
x.dtype

dtype('int64')

ndim pokazuje ilość wymiarów w tablicy

In [16]:
x.ndim

2

In [17]:
x.shape

(4, 3)

`ndim` stands for "number of dimensions". It's an attribute of NumPy arrays that tells you how many dimensions the array has. For example, a 1D array (like a list of numbers) has `ndim` equal to 1, a 2D array (like a matrix) has `ndim` equal to 2, and so on.

The `shape` attribute of a NumPy array tells you the size of the array in each dimension. It's a tuple of integers. For a 2D array, the shape will be `(rows, columns)`.

In [18]:
x = np.array(

   [
    [[4,3,1],
     [5,8,7]],

     [[5,8,9],
      [4,8,6]],

    [[1,8,3],
     [4,7,9]]
    ])
x

array([[[4, 3, 1],
        [5, 8, 7]],

       [[5, 8, 9],
        [4, 8, 6]],

       [[1, 8, 3],
        [4, 7, 9]]])

In [19]:
x.shape

(3, 2, 3)

In [20]:
x.ndim

3

In [21]:
import numpy as np
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.full(shape=(3, 3), fill_value=5, dtype='int')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [26]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [28]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [31]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [32]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [33]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
A.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [38]:
A + B

array([6, 0, 7, 4])

In [39]:
A-B

array([0, 2, 1, 0])

In [40]:
A*B

array([ 9, -1, 12,  4])

In [41]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [42]:
A+3

array([6, 4, 7, 5])

In [43]:
2*A

array([6, 2, 8, 4])

In [44]:
A+ 3*B

array([12, -2, 13,  8])

In [46]:
np.add(A,B)

array([6, 0, 7, 4])

In [47]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [48]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [49]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [53]:
np.any([0,0,0])

np.False_

INDEKSOWANIE

In [55]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
A[2]

np.int64(2)

In [61]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [62]:
A[:2]

array([0, 1])

In [64]:
A[[0,2]]

array([0, 2])

In [65]:
A[-1]

np.int64(19)

In [66]:
A[10:15]

array([10, 11, 12, 13, 14])

In [67]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
A[0]

array([0, 1, 2, 3, 4])

In [70]:
A[1]

array([5, 6, 7, 8, 9])

In [74]:
A[:,-2]

array([ 3,  8, 13, 18])

In [77]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])