<a href="https://colab.research.google.com/github/sztabamarta-lgtm/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type (x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [17]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

2D Array

In [31]:
x = np.array([[1, 2,3], [-3, 1,3], [5, 6,8], [7,8,9]])
print(x)
x

[[ 1  2  3]
 [-3  1  3]
 [ 5  6  8]
 [ 7  8  9]]


array([[ 1,  2,  3],
       [-3,  1,  3],
       [ 5,  6,  8],
       [ 7,  8,  9]])

In [32]:
x.dtype

dtype('int64')

ndim pokazuje ilość wymiarów w tablicy

In [35]:
x.ndim

2

In [34]:
x.shape

(4, 3)

`ndim` stands for "number of dimensions". It's an attribute of NumPy arrays that tells you how many dimensions the array has. For example, a 1D array (like a list of numbers) has `ndim` equal to 1, a 2D array (like a matrix) has `ndim` equal to 2, and so on.

The `shape` attribute of a NumPy array tells you the size of the array in each dimension. It's a tuple of integers. For a 2D array, the shape will be `(rows, columns)`.

In [37]:
x = np.array(

   [
    [[4,3,1],
     [5,8,7]],

     [[5,8,9],
      [4,8,6]],

    [[1,8,3],
     [4,7,9]]
    ])
x

array([[[4, 3, 1],
        [5, 8, 7]],

       [[5, 8, 9],
        [4, 8, 6]],

       [[1, 8, 3],
        [4, 7, 9]]])

In [38]:
x.shape

(3, 2, 3)

In [39]:
x.ndim

3

In [5]:
import numpy as np
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full(shape=(3, 3), fill_value=5, dtype='int')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [18]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [20]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [21]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
A.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])